#!/usr/bin/env bash
# Render iOS App Store marketing screenshots from real Simulator captures.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
HTML_DIR="$ROOT/html"
SHOT_IPHONE="$ROOT/screenshots/iphone"
SHOT_IPAD="$ROOT/screenshots/ipad"
RAW_IPHONE="$ROOT/raw/iphone"
RAW_IPAD="$ROOT/raw/ipad"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

if [[ ! -x "$CHROME" ]]; then
  echo "Google Chrome not found at $CHROME" >&2
  exit 1
fi

# App Store Connect accepted iPhone portrait sizes:
#   1284×2778  (6.7")  — primary
#   1242×2688  (6.5")  — alternate
# Landscape: 2778×1284 or 2688×1242 (not generated by default)
IPHONE_W=1284
IPHONE_H=2778
IPHONE_65_W=1242
IPHONE_65_H=2688

SHOT_IPHONE_67="$ROOT/screenshots/iphone-6.7"
SHOT_IPHONE_65="$ROOT/screenshots/iphone-6.5"
CLEAN_IPHONE_67="$ROOT/screenshots/iphone-6.7-clean"
CLEAN_IPHONE_65="$ROOT/screenshots/iphone-6.5-clean"
CLEAN_IPHONE="$ROOT/screenshots/iphone-clean"

mkdir -p "$SHOT_IPHONE" "$SHOT_IPAD" "$SHOT_IPHONE_67" "$SHOT_IPHONE_65" \
  "$CLEAN_IPHONE" "$CLEAN_IPHONE_67" "$CLEAN_IPHONE_65" "$HTML_DIR/generated"

# Scene metadata: file_stem|shot_class|eyebrow|headline (use <br/>)|subhead
SCENES=(
  "01-home|shot-1|Simple MP3|Your music.<br/>Your car. Offline.|Playlists that feel premium — ready for CarPlay"
  "02-playlists|shot-2|Playlists|Organize like<br/>a pro|Create collections and take every mix on the road"
  "03-nowplaying|shot-3|Now Playing|Immersive<br/>playback|Queue, shuffle, resume, and big controls when you need them"
  "04-drive|shot-4|Drive Mode|Built for<br/>the drive|Large tap targets and glanceable now-playing for the road"
  "05-carplay|shot-5|CarPlay|Dash-ready<br/>control|Browse playlists, Jellyfin Offline &amp; songs from CarPlay"
  "06-jellyfin|shot-6|Jellyfin|Sync offline<br/>from your server|Import from your LAN media server and play without the cloud"
)

render_chrome() {
  local html_file="$1"
  local out="$2"
  local w="$3"
  local h="$4"
  local abs
  abs="$(cd "$(dirname "$html_file")" && pwd)/$(basename "$html_file")"
  echo "→ $out (${w}x${h})"
  "$CHROME" \
    --headless=new \
    --disable-gpu \
    --hide-scrollbars \
    --force-device-scale-factor=1 \
    --default-background-color=00000000 \
    --window-size="${w},${h}" \
    --screenshot="$out" \
    "file://${abs}" \
    2>/dev/null
  # Ensure exact size (Chrome sometimes differs by a pixel)
  sips -z "$h" "$w" "$out" >/dev/null 2>&1 || true
}

write_html() {
  local device="$1"   # iphone | ipad
  local raw_dir="$2"
  local stem="$3"
  local shot_class="$4"
  local eyebrow="$5"
  local headline="$6"
  local subhead="$7"
  local out_html="$HTML_DIR/generated/${device}-${stem}.html"
  local img_rel="../../raw/${device}/${stem}.png"
  local page_class body_pad

  if [[ "$device" == "iphone" ]]; then
    page_class="iphone-page"
    body_pad="iphone"
  else
    page_class="ipad-page"
    body_pad="ipad"
  fi

  if [[ ! -f "$raw_dir/${stem}.png" ]]; then
    echo "Skip missing raw capture: $raw_dir/${stem}.png" >&2
    return 1
  fi

  cat > "$out_html" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="../styles-ios.css" />
</head>
<body class="${page_class}">
  <div class="shot ${body_pad} ${shot_class}">
    <div class="glow"></div>
    <div class="copy">
      <div class="eyebrow">${eyebrow}</div>
      <h1 class="headline">${headline}</h1>
      <p class="subhead">${subhead}</p>
    </div>
    <div class="device-wrap">
      <div class="device">
        <div class="device-screen">
          <img src="${img_rel}" alt="${stem}" />
        </div>
      </div>
    </div>
    <div class="brand"><div class="brand-dot"></div><span>SIMPLE MP3</span></div>
  </div>
</body>
</html>
EOF
  echo "$out_html"
}

echo "Rendering iPhone marketing screenshots (${IPHONE_W}×${IPHONE_H})…"
for entry in "${SCENES[@]}"; do
  IFS='|' read -r stem shot_class eyebrow headline subhead <<<"$entry"
  if html="$(write_html iphone "$RAW_IPHONE" "$stem" "$shot_class" "$eyebrow" "$headline" "$subhead")"; then
    render_chrome "$html" "$SHOT_IPHONE/${stem}.png" "$IPHONE_W" "$IPHONE_H"
    cp -f "$SHOT_IPHONE/${stem}.png" "$SHOT_IPHONE_67/${stem}.png"
    # 6.5" alternate size required by some App Store Connect slots
    sips -z "$IPHONE_65_H" "$IPHONE_65_W" "$SHOT_IPHONE/${stem}.png" --out "$SHOT_IPHONE_65/${stem}.png" >/dev/null
    echo "→ $SHOT_IPHONE_65/${stem}.png (${IPHONE_65_W}x${IPHONE_65_H})"
  fi
done

echo ""
echo "Rendering iPad marketing screenshots (2064×2752)…"
for entry in "${SCENES[@]}"; do
  IFS='|' read -r stem shot_class eyebrow headline subhead <<<"$entry"
  if html="$(write_html ipad "$RAW_IPAD" "$stem" "$shot_class" "$eyebrow" "$headline" "$subhead")"; then
    render_chrome "$html" "$SHOT_IPAD/${stem}.png" 2064 2752
  fi
done

# Clean full-bleed App Store sizes (no marketing chrome) — preferred upload
CLEAN_IPAD="$ROOT/screenshots/ipad-clean"
mkdir -p "$CLEAN_IPHONE" "$CLEAN_IPAD" "$CLEAN_IPHONE_67" "$CLEAN_IPHONE_65"

echo ""
echo "Exporting clean full-bleed iPhone sizes (1284×2778 + 1242×2688)…"
for entry in "${SCENES[@]}"; do
  IFS='|' read -r stem _ <<<"$entry"
  if [[ -f "$RAW_IPHONE/${stem}.png" ]]; then
    sips -z "$IPHONE_H" "$IPHONE_W" "$RAW_IPHONE/${stem}.png" --out "$CLEAN_IPHONE/${stem}.png" >/dev/null
    cp -f "$CLEAN_IPHONE/${stem}.png" "$CLEAN_IPHONE_67/${stem}.png"
    sips -z "$IPHONE_65_H" "$IPHONE_65_W" "$RAW_IPHONE/${stem}.png" --out "$CLEAN_IPHONE_65/${stem}.png" >/dev/null
    echo "→ clean ${stem}.png  ${IPHONE_W}x${IPHONE_H}  +  ${IPHONE_65_W}x${IPHONE_65_H}"
  fi
  if [[ -f "$RAW_IPAD/${stem}.png" ]]; then
    sips -z 2752 2064 "$RAW_IPAD/${stem}.png" --out "$CLEAN_IPAD/${stem}.png" >/dev/null
    echo "→ $CLEAN_IPAD/${stem}.png"
  fi
done

echo ""
echo "Done. iPhone primary size: ${IPHONE_W}×${IPHONE_H} (also 1242×2688 under iphone-6.5*)"
ls -la "$SHOT_IPHONE" "$CLEAN_IPHONE" "$SHOT_IPAD" 2>/dev/null || true
